# Note: this file is generated by chatGPT and needs testing. 
import requests

APP_ID = 'your_app_id'
APP_SECRET = 'your_app_secret'
LONG_LIVED_USER_TOKEN = 'your_current_long_lived_user_token'

def get_new_long_lived_user_token():
    url = f"https://graph.facebook.com/v19.0/oauth/access_token"
    params = {
        'grant_type': 'fb_exchange_token',
        'client_id': APP_ID,
        'client_secret': APP_SECRET,
        'fb_exchange_token': LONG_LIVED_USER_TOKEN
    }
    response = requests.get(url, params=params)
    response.raise_for_status()
    data = response.json()
    new_user_token = data['access_token']
    print(f"✅ New long-lived user token: {new_user_token}")
    return new_user_token

def get_page_access_token(user_token):
    url = f"https://graph.facebook.com/v19.0/me/accounts"
    params = {
        'access_token': user_token
    }
    response = requests.get(url, params=params)
    response.raise_for_status()
    data = response.json()
    for page in data['data']:
        print(f"✅ Page: {page['name']}")
        print(f"➡ Page ID: {page['id']}")
        print(f"➡ Page Access Token: {page['access_token']}")
    return data

if __name__ == "__main__":
    new_user_token = get_new_long_lived_user_token()
    get_page_access_token(new_user_token)
